name: Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup - Depedencies
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl libprotobuf-dev protobuf-compiler

      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          rustup default nightly
          rustup update nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: GCS Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCS_SA_KEY }}

      - name: Setup - gcloud/gsutil
        uses: google-github-actions/setup-gcloud@v1

      - name: Sync Cache
        run: |
          mkdir target
          gsutil rsync -r gs://fusotao-compile-cache/ubuntu-20 target

      - name: Run All Unit-tests
        run: |
          cargo test --release

      - name: Upload Cache
        run: |-
          gsutil rsync -r target gs://fusotao-compile-cache/ubuntu-20
