name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-release:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-12-22
          override: true
          target: wasm32-unknown-unknown
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: montudor/action-zip@v1
        with:
          args: zip -j -r fusotao.zip target/release/fuso *.spec README.md LICENSE
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fusotao.zip
          tag: ${{ github.ref }}
          overwrite: true
