name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-release:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl jq

      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          rustup default stable
          rustup update nightly
          rustup update stable
          rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Build
        run: |
          cargo build --release

      - name: Build Chain Spec
        run: |
          code=$(target/release/fuso build-spec --chain local | jq .genesis.runtime.system.code)
          sed -i ".bak" -f - fusotao-*.json << EOF
          s/{{code}}/$code/g
          EOF
          target/release/fuso build-spec --raw --chain fusotao-brandy.json > resources/octopus-testnet.json
          target/release/fuso build-spec --raw --chain fusotao-mainnet.json > resources/octopus-mainnet.json

      - uses: montudor/action-zip@v1
        with:
          args: zip -j -r fusotao.zip target/release/fuso target/release/wbuild/fuso-runtime/fuso_runtime.compact.compressed.wasm fusotao-*.json README.md LICENSE

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fusotao.zip
          tag: ${{ github.ref }}
          overwrite: true
